In [1]:
import torch
torch.__version__

'2.5.1'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# We can check the dimensions of a tensor using the ndim attribute.

scalar.ndim  

0

In [4]:
# To retrieve the number from the tensor use item() method

scalar.item()

7

In [5]:
vector = torch.tensor([9,7])
vector

tensor([9, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
mat = torch.tensor([[7,8],
                   [9,10]])
mat

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
mat.ndim

2

In [10]:
mat.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
# The dimensions go outer to inner.

# That means there's 1 dimension of 3 by 3.

TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
random_tensor = torch.rand(size=(3,4))
random_tensor , random_tensor.dtype, random_tensor.shape

(tensor([[0.0561, 0.6807, 0.6417, 0.9416],
         [0.1742, 0.8485, 0.0321, 0.7840],
         [0.6591, 0.4293, 0.5207, 0.7643]]),
 torch.float32,
 torch.Size([3, 4]))

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zero = torch.zeros(size=(3,4))
zero , zero.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
one = torch.ones(size=(3,3))
one, one.dtype, one.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 3]))

In [21]:
a = torch.range(0,10)
a = torch.arange(start=0, end=10, step=1)
a

/tmp/ipykernel_13485/1462387123.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ten_zeros = torch.zeros_like(input = a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [27]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")  # Default will be CPU

tensor([[0.5803, 0.2150, 0.2669, 0.4548],
        [0.9581, 0.5037, 0.1158, 0.9150],
        [0.0584, 0.9909, 0.0043, 0.7377]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [38]:
a = torch.tensor([1,2,3])
a + 10

tensor([11, 12, 13])

In [39]:
a * 10

tensor([10, 20, 30])

In [40]:
a

tensor([1, 2, 3])

In [41]:
a = a-10
a

tensor([-9, -8, -7])

In [43]:
a = a + 10
a 

tensor([1, 2, 3])

In [44]:
torch.multiply(a,10)

tensor([10, 20, 30])

In [46]:
## Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)

print(a, "*", a)
print("Equals: ", a*a)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [47]:
'''
The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

'''

'\nThe difference between element-wise multiplication and matrix multiplication is the addition of values.\n\nFor our tensor variable with values [1, 2, 3]:\n\nOperation\tCalculation\tCode\nElement-wise multiplication\t[1*1, 2*2, 3*3] = [1, 4, 9]\ttensor * tensor\nMatrix multiplication\t[1*1 + 2*2 + 3*3] = [14]\ttensor.matmul(tensor)\n\n'

In [48]:
a * a

tensor([1, 4, 9])

In [49]:
torch.matmul(a,a)

tensor(14)

In [51]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
a @ a

tensor(14)

In [53]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(a)):
  value += a[i] * a[i]
value

CPU times: user 418 μs, sys: 1.09 ms, total: 1.5 ms
Wall time: 5.04 ms


tensor(14)

In [54]:
%%time
torch.matmul(a, a)

CPU times: user 260 μs, sys: 38 μs, total: 298 μs
Wall time: 230 μs


tensor(14)

In [55]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [57]:
# View tensor_A and tensor_B.T  --> Transpose
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [58]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [59]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [62]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [63]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [67]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [68]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [71]:
tensor = torch.arange(10., 100., 10.)
tnsr_float16 = tensor.type(torch.float16)
tnsr_int8 = tensor.type(torch.int8)
tnsr_float16, tnsr_int8

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16),
 tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8))

In [72]:
import torch
torch.cuda.is_available()

False

In [73]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [75]:
'''
Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

Method	One-line description
torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.
'''

"\nReshaping, stacking, squeezing and unsqueezing\nOften times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.\n\nTo do so, some popular methods are:\n\nMethod\tOne-line description\ntorch.reshape(input, shape)\tReshapes input to shape (if compatible), can also use torch.Tensor.reshape().\n\nTensor.view(shape)\tReturns a view of the original tensor in a different shape but shares the same data as the original tensor.\n\ntorch.stack(tensors, dim=0)\tConcatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.\n\ntorch.squeeze(input)\tSqueezes input to remove all the dimenions with value 1.\n\ntorch.unsqueeze(input, dim)\tReturns input with a dimension value of 1 added at dim.\n\ntorch.permute(input, dims)\tReturns a view of the original input with its dimensions permuted (rearranged) to dims.\n"

In [76]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [78]:
#Add an extra dimension 

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [80]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [82]:
# So changing the view changes the original tensor too.

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [83]:
#If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().


x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [84]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [88]:
#How about removing all single dimensions from a tensor?

# To do so you can use torch.squeeze() 
# (I remember this as squeezing the tensor to only have dimensions over 1).


print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extradimension from x_reshaped

x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous tensor: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New tensor: torch.Size([7])


In [89]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [91]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [92]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [93]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [94]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
# tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [97]:
tensor = tensor + 2
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))