In [1]:
import torch

In [2]:
# The autograd package provides automatic differentiation 
# for all operations on Tensors

# requires_grad = True -> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True)
y = x + 2

In [3]:
# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([ 0.7590, -0.6489, -1.1758], requires_grad=True)
tensor([2.7590, 1.3511, 0.8242], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 3
print(z)
z = z.mean()
print(z)


tensor([22.8354,  5.4767,  2.0380], grad_fn=<MulBackward0>)
tensor(10.1167, grad_fn=<MeanBackward0>)


1. Let's compute the gradients with backpropagation
2. When we finish our computation we can call .backward() and have all the gradients computed automatically.
3. The gradient for this tensor will be accumulated into .grad attribute.
4. It is the partial derivate of the function w.r.t. the tensor

In [ ]:
z.backward()
print(x.grad)  #dz/dx

tensor([5.5179, 2.7023, 1.6485])


In [6]:
x = torch.randn(3, requires_grad=True)

y = x * 2
for _ in range(10):
    y = y * 2

print(y)
print(y.shape)

tensor([  997.6085,   352.5207, -1501.1711], grad_fn=<MulBackward0>)
torch.Size([3])


In [7]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])
